### ISSUE TITLE
Update hook not working after the upgrade

### ISSUE THREAD

**Issue by RemiZlatinis** [RemiZlatinis/service_status_indicator#4]
After running the installation/upgrade script the refresh hook stops working. The problem lies in the database module. 

```
Traceback (most recent call last):
  File "/etc/service-status-indicator/src/cli.py", line 191, in <module>
    cli(prog_name='ssi')
  File "/etc/service-status-indicator/src/.env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/service-status-indicator/src/.env/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/etc/service-status-indicator/src/.env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/service-status-indicator/src/.env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/service-status-indicator/src/.env/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/service-status-indicator/src/cli.py", line 161, in refresh
    DB.set_running(service_id, False)
  File "/etc/service-status-indicator/src/database.py", line 127, in set_running
    saved['id'],
    ~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by RemiZlatinis** [comment]
Trying to refresh a disabled service?

- [x] Check if the corresponding service is enabled before using the refresh hook `sudo ssi services -d`, if is not enabled it `sudo ssi enable {service-id}`.
